version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: always

  backend:
    image: shurshalo/foodgram-project-react_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media

    restart: always

  frontend:
    image: shurshalo/foodgram-project-react_frontend
    env_file: .env
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    depends_on:
      - frontend
      - backend
    image: shurshalo/foodgram-project-react_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - 8001:80
    restart: always