version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: /home/yc-user/foodgram-project-react/frontend
      dockerfile: Dockerfile
    volumes:
      - /home/yc-user/foodgram-project-react/frontend:/app/result_build/

  backend:
    depends_on:
      - db
    build: /home/yc-user/foodgram-project-react/backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    restart: always

  nginx:
    build: /home/yc-user/foodgram-project-react/nginx
    depends_on:
      - backend
      - db
    ports:
      - "8000:80"
    volumes:
      - /home/yc-user/foodgram-project-react/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/yc-user/foodgram-project-react/frontend/build:/usr/share/nginx/html/
      - /home/yc-user/foodgram-project-react/docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/media/
    restart: always