version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: always

  frontend:
    image: shurshalo/foodgram-project-react_frontend
    context: ./frontend
    dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  backend:
    depends_on:
      - db
    image: shurshalo/foodgram-project-react_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    restart: always

  nginx:
    image: shurshalo/foodgram-project-react_gateway
    depends_on:
      - backend
      - db
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/media/
    restart: always