# Generated by Django 3.2.16 on 2023-11-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0002_auto_20231115_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='food.recipe',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='recipe',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='food.recipe',
            ),
            preserve_default=False,
        ),
    ]
