# Generated by Django 3.2.16 on 2023-11-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0005_auto_20231128_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredients',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredient',
                to='food.ingredient',
                verbose_name='Ингредиент',
            ),
        ),
    ]
