# Generated by Django 3.2.16 on 2023-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0006_auto_20231116_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                upload_to='food/images', verbose_name='Фото'
            ),
        ),
    ]
