# Generated by Django 3.2.16 on 2023-11-17 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0010_auto_20231117_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='name',
        ),
    ]
