# Generated by Django 3.2.16 on 2023-11-17 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0016_auto_20231117_1811'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_following',
        ),
    ]
