# Generated by Django 3.2.16 on 2023-11-19 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0019_auto_20231119_1823'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_following',
        ),
    ]
