# Generated by Django 3.2.16 on 2023-11-19 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0020_remove_follow_unique_user_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shopping',
            name='unique_user_shopping',
        ),
    ]
