# Generated by Django 3.2.16 on 2023-11-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0021_auto_20231119_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={
                'verbose_name': 'Связь рецепта и ингредиента',
                'verbose_name_plural': 'Связь рецептов и ингредиентов',
            },
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite',
                to='food.recipe',
                verbose_name='Рецепт',
            ),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='following',
                to=settings.AUTH_USER_MODEL,
                verbose_name='На кого подписан',
            ),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Текущий пользователь',
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredients',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipeingredients',
                to='food.ingredient',
                verbose_name='Ингредиент',
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipeingredients',
                to='food.recipe',
                verbose_name='Рецепт',
            ),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shopping',
                to='food.recipe',
                verbose_name='Рецепт',
            ),
        ),
    ]
