# Generated by Django 3.2.16 on 2023-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0023_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True, default=1, verbose_name='Дата публикации'
            ),
            preserve_default=False,
        ),
    ]
