# Generated by Django 3.2.16 on 2023-11-24 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0024_auto_20231124_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
    ]
