# Generated by Django 3.2.16 on 2023-11-15 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username&email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
